# Rocks analysis demo. 

* Add instruction here or in readme for how to set up your own analysis pipeline.

In [1]:
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd
import seaborn as sns
from datetime import datetime
import numpy as np

# Jupyter Lab imports.
import ipywidgets as widgets
from ipywidgets import interact, interact_manual, fixed

# Path to local imports.
sys.path.append("/home/drew/He6CRES/rocks_analysis_pipeline/")
from results import ExperimentResults
from rocks_utility import he6cres_db_query

## Step 0: Query the postgres database to see what run_ids to analyze.

In [3]:
query_run_log = '''
                    SELECT run_id, run_notes, set_field, created_at, EXTRACT(MONTH from created_at::date) as month
                    FROM he6cres_runs.run_log
                    WHERE num_spec_acq = 100 AND
                    EXTRACT(MONTH from created_at::date) = 8
                    ORDER BY run_id DESC 
                    LIMIT 80
                  '''

run_log = he6cres_db_query(query_run_log, local = True)

first_rid_per_field = run_log.groupby(["set_field"]).count()
display(first_rid_per_field)
display(run_log[-30:])

he6_run_list = run_log.run_id.to_list()
he6_field_list = run_log.set_field.to_list()

print(" ".join(str(x) for x in he6_run_list[-57:]))
print(f"\n\n{len(he6_run_list)}")
print(" ".join(str(x) for x in he6_field_list[-57:]))

           run_id  run_notes  created_at  month
set_field
-3.25           8          8           8      8
-3.00           5          5           5      5
-2.75           6          6           6      6
-2.50           5          5           5      5
-2.25           5          5           5      5
-2.00           5          5           5      5
-1.75           6          6           6      6
-1.50           5          5           5      5
-1.25           5          5           5      5
-1.00           5          5           5      5
-0.75           5          5           5      5

,run_id,run_notes,set_field,created_at,month
30,405,-2.00T - 1/5,-2.00,2022-08-18 10:19:22.446809,8.0
31,403,-2.25T - 5/5,-2.25,2022-08-18 09:34:34.768423,8.0
32,402,-2.25T - 4/5,-2.25,2022-08-18 09:29:00.574241,8.0
33,401,-2.25T - 3/5,-2.25,2022-08-18 09:23:22.583125,8.0
34,400,-2.25T - 2/5,-2.25,2022-08-18 09:16:46.136655,8.0
35,399,-2.25T - 1/5,-2.25,2022-08-18 09:10:07.173661,8.0
36,397,-2.50T - 5/5,-2.50,2022-08-18 08:15:38.384629,8.0
37,396,-2.50T - 4/5,-2.50,2022-08-18 08:09:34.383221,8.0
38,395,-2.50T - 3/5,-2.50,2022-08-18 08:01:12.036577,8.0
39,394,-2.50T - 2/5,-2.50,2022-08-18 07:55:33.409386,8.0
40,393,-2.50T - 1/5,-2.50,2022-08-18 07:48:01.891288,8.0
41,391,-2.75T - 5/5,-2.75,2022-08-18 07:03:13.349592,8.0
42,390,-2.75T - 4/5,-2.75,2022-08-18 06:57:00.997868,8.0
43,389,-2.75T - 3/5,-2.75,2022-08-18 06:51:14.635788,8.0
44,388,-2.75T - 2/5,-2.75,2022-08-18 06:37:35.240507,8.0
45,387,-2.75T - 1/5,-2.75,2022-08-18 06:31:38.473669,8.0
46,385,-2.75T - 1/5,-2.75,2022-08-18 06:18:07.945578,8.0
47,384,-3T - 5/5,-3.00,2022-08-18 05:21:55.274899,8.0
48,383,-3T - 4/5,-3.00,2022-08-18 05:15:49.504073,8.0
49,382,-3T - 3/5,-3.00,2022-08-18 05:10:29.219905,8.0
50,381,-3T - 2/5,-3.00,2022-08-18 05:04:54.048464,8.0
51,380,-3T - 1/5,-3.00,2022-08-18 04:58:33.154671,8.0
52,377,"-3.25T, 5/5.",-3.25,2022-08-18 04:12:10.383485,8.0
53,376,"-3.25T, 4/5.",-3.25,2022-08-18 04:03:47.606144,8.0
54,375,"-3.25T, 3/5.",-3.25,2022-08-18 03:55:33.738509,8.0
55,374,"-3.25T, 2/5.",-3.25,2022-08-18 03:44:53.169207,8.0
56,373,"-3.25T, 1/5.",-3.25,2022-08-18 03:36:35.927806,8.0
57,365,100 files (3/5). 3.25T. Increased monitor inte...,-3.25,2022-08-17 23:38:50.198819,8.0
58,364,100 files (2/5). 3.25T. Temp of target was get...,-3.25,2022-08-17 23:25:58.273621,8.0
59,363,100 files (1/5). 3.25T.,-3.25,2022-08-17 23:02:33.903197,8.0

437 436 434 433 432 431 430 428 427 426 425 424 422 421 420 419 418 416 415 414 413 412 411 409 408 407 406 405 403 402 401 400 399 397 396 395 394 393 391 390 389 388 387 385 384 383 382 381 380 377 376 375 374 373 365 364 363


60
-0.75 -0.75 -1.0 -1.0 -1.0 -1.0 -1.0 -1.25 -1.25 -1.25 -1.25 -1.25 -1.5 -1.5 -1.5 -1.5 -1.5 -1.75 -1.75 -1.75 -1.75 -1.75 -1.75 -2.0 -2.0 -2.0 -2.0 -2.0 -2.25 -2.25 -2.25 -2.25 -2.25 -2.5 -2.5 -2.5 -2.5 -2.5 -2.75 -2.75 -2.75 -2.75 -2.75 -2.75 -3.0 -3.0 -3.0 -3.0 -3.0 -3.25 -3.25 -3.25 -3.25 -3.25 -3.25 -3.25 -3.25

## Step 1: Analyze the run_ids. 

* Follow the instructions in the [readme](https://github.com/Helium6CRES/rocks_analysis_pipeline).

## Step 2: Visualize the results and/or build a spectrum.

### 2a: Grab the experiment directory and root files from rocks.

In [14]:
local_dir = "/media/drew/T7 Shield/rocks_analysis/saved_experiments"
experiment_name = "he6_275_test"
analysis_id = 0
include_root_files = True
max_root_files_to_grab = 5
rebuild_experiment_dir = False

In [15]:
exp_results_demo = ExperimentResults(local_dir = local_dir, 
                                     experiment_name = experiment_name, 
                                     analysis_id = analysis_id, 
                                     include_root_files = include_root_files,
                                     max_root_files_to_grab = max_root_files_to_grab,
                                     rebuild_experiment_dir=rebuild_experiment_dir,
                                    )

Copying analysis directory from rocks. This may take a few minutes.


Collecting root_files, tracks, and events.

Making /media/drew/T7 Shield/rocks_analysis/saved_experiments/he6_275_test_aid_0/root_files
Copying from remote path:  /data/eliza4/he6_cres/katydid_analysis/root_files/rid_0387/aid_000/Freq_data_2022-08-17-23-26-01_000.root
Got above file. Put it: /media/drew/T7 Shield/rocks_analysis/saved_experiments/he6_275_test_aid_0/root_files/Freq_data_2022-08-17-23-26-01_000.root
Copying from remote path:  /data/eliza4/he6_cres/katydid_analysis/root_files/rid_0387/aid_000/Freq_data_2022-08-17-23-26-03_000.root
Got above file. Put it: /media/drew/T7 Shield/rocks_analysis/saved_experiments/he6_275_test_aid_0/root_files/Freq_data_2022-08-17-23-26-03_000.root
Copying from remote path:  /data/eliza4/he6_cres/katydid_analysis/root_files/rid_0387/aid_000/Freq_data_2022-08-17-23-26-06_000.root
Got above file. Put it: /media/drew/T7 Shield/rocks_analysis/saved_experiments/he6_275_test_aid_0/root_files/Freq_data_2022-08-17-23-26-06_000.root
Copying from remote path:  /data/eliza4/he6_cres/katydid_analysis/root_files/rid_0387/aid_000/Freq_data_2022-08-17-23-26-09_000.root
Got above file. Put it: /media/drew/T7 Shield/rocks_analysis/saved_experiments/he6_275_test_aid_0/root_files/Freq_data_2022-08-17-23-26-09_000.root
Copying from remote path:  /data/eliza4/he6_cres/katydid_analysis/root_files/rid_0387/aid_000/Freq_data_2022-08-17-23-26-12_000.root
Got above file. Put it: /media/drew/T7 Shield/rocks_analysis/saved_experiments/he6_275_test_aid_0/root_files/Freq_data_2022-08-17-23-26-12_000.root
Closing sftp connection to rocks.
Closing ssh connection to rocks.

### 2b: Look at the attributes of the exp_results_demo object.

In [16]:
exp_results_demo.root_files.head(3)

,run_id,spec_id,file_path,true_field,analysis_id,root_file_exists,file_id,rocks_file_path,exists,approx_slope,...,base_config_path,output_dir,noise_file_path,rocks_noise_file_path,root_file_path,pst_time,utc_time,monitor_rate,field,set_field
0,387,7274,/mnt/sdb/data/Freq_data_2022-08-17-23-26-01.spec,2.749999,0,True,0,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,True,1.063324e+11,...,/data/eliza4/he6_cres/katydid_analysis/base_co...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,/mnt/sdb/data/Freq_data_2022-08-18-11-31-49.spec,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,2022-08-17 23:26:01-07:00,2022-08-18 06:26:01+00:00,51157.00,2.750001,2.75
1,387,7275,/mnt/sdc/data/Freq_data_2022-08-17-23-26-03.spec,2.749999,0,True,1,/data/eliza4/he6_cres/sdc/data/Freq_data_2022-...,True,1.063324e+11,...,/data/eliza4/he6_cres/katydid_analysis/base_co...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,/mnt/sdb/data/Freq_data_2022-08-18-11-31-49.spec,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,2022-08-17 23:26:03-07:00,2022-08-18 06:26:03+00:00,52826.17,2.750001,2.75
2,387,7276,/mnt/sdd/data/Freq_data_2022-08-17-23-26-06.spec,2.749999,0,True,2,/data/eliza4/he6_cres/sdd/data/Freq_data_2022-...,True,1.063324e+11,...,/data/eliza4/he6_cres/katydid_analysis/base_co...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,/mnt/sdb/data/Freq_data_2022-08-18-11-31-49.spec,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,2022-08-17 23:26:06-07:00,2022-08-18 06:26:06+00:00,50436.00,2.750001,2.75

In [17]:
exp_results_demo.tracks.head(3)

,UniqueID,Bits,Component,AcquisitionID,TrackID,EventID,EventSequenceID,IsCut,StartTimeInRunC,StartTimeInAcq,...,FreqIntc,TimeIntc,MeanTrackSNR,set_field,TimeIntc_mean,TimeIntc_std,TimeLength_mean,TimeLength_std,Slope_mean,Slope_std
0,0.0,50331648.0,0.0,0.0,68.0,1.0,-1.0,0.0,0.046370,0.046370,...,-4.907959e+09,0.045416,11.836900,2.75,0.045431,0.000238,0.000047,0.000024,1.070308e+11,4.581828e+09
1,0.0,50331648.0,0.0,0.0,69.0,1.0,-1.0,0.0,0.046466,0.046466,...,-4.885272e+09,0.045412,12.451830,2.75,0.045431,0.000238,0.000047,0.000024,1.070308e+11,4.581828e+09
2,0.0,50331648.0,0.0,0.0,70.0,1.0,-1.0,0.0,0.046486,0.046486,...,-4.790800e+09,0.045390,11.094001,2.75,0.045431,0.000238,0.000047,0.000024,1.070308e+11,4.581828e+09

In [8]:
exp_results_demo.events.head(3)

,run_id,file_id,EventID,EventStartTime,EventEndTime,EventStartFreq,EventEndFreq,EventTimeLength,EventFreqLength,EventTrackCoverage,EventMeanSNR,EventSlope,EventNBins,EventTrackTot,EventFreqIntc,EventTimeIntc,field,set_field,monitor_rate
0,373,0,1,0.024989,0.027051,5.220255e+08,8.900276e+08,0.002062,3.680021e+08,0.695364,10.758913,1.784985e+11,55.0,12,-3.938476e+09,0.022064,3.249954,3.25,58525.0
1,373,0,2,0.048370,0.054460,1.024997e+08,1.186159e+09,0.006089,1.083660e+09,1.033632,12.568884,1.779588e+11,381.0,77,-8.505428e+09,0.047794,3.249954,3.25,58525.0
2,373,0,3,0.120849,0.123081,6.125950e+08,1.009885e+09,0.002232,3.972896e+08,1.079511,10.880306,1.779716e+11,60.0,12,-2.089511e+10,0.117407,3.249954,3.25,58525.0

## Are all the desired fields present?

In [5]:
exp_results_demo.run_ids

[373, 380, 385, 393, 399, 405, 411, 418, 424, 430, 436]

In [9]:
exp_results_demo.root_files.groupby(["set_field"]).root_file_exists.sum().reset_index()

    set_field  root_file_exists
0        0.75               100
1        1.00               100
2        1.25               100
3        1.50                99
4        1.75               100
5        2.00               100
6        2.25               100
7        2.50               100
8        2.75               100
9        3.00               100
10       3.25               100

### 2c: Visualize the quality of track and event reconstruction.

In [18]:
%matplotlib widget

plt.rcParams['figure.dpi']= 100

@interact
def analysis_viz(
    run_id = widgets.Select(options = exp_results_demo.run_ids, description='run_id: '),
    file_id = widgets.Select(options = exp_results_demo.file_ids, description='file_id: '),
    events = widgets.Checkbox(True, description='events'),
    tracks = widgets.Checkbox(False, description='tracks'),
    sparse = widgets.Checkbox(False, description='sparse_spec'),
    EventID = widgets.IntSlider(value=1,min=1,max=20,step=1),
    mrk_sz = widgets.FloatSlider(value=.08,min=0,max=1.0,step=1e-2),
    alpha = widgets.FloatSlider(value=1.0,min=0.0,max=1.0,step=1e-2), 
    frac_pts = widgets.FloatSlider(value=.7,min=0.0,max=1.0,step=1e-2),
):

    config = {"tracks": {"show": tracks,  "alpha": alpha, "EventIDs":[EventID]}, 
              "events": {"show": events, "alpha": alpha}, 
              "sparse_spec": {"show": sparse, "frac_pts": frac_pts,  "alpha": alpha, "mrk_sz": mrk_sz}}
    
    exp_results_demo.visualize(run_id, file_id, config)

interactive(children=(Select(description='run_id: ', options=(387,), value=387), Select(description='file_id: …

### 2d: Visualize the relationship between different track attributes.

In [12]:
%matplotlib widget

set_fields = sorted(exp_results_demo.tracks['set_field'].unique().tolist())

plt.rcParams['figure.dpi']= 100
@interact
def scatter_plots(
    field = widgets.Select(options = set_fields,  description='set_field: '),
    column_1 = widgets.Select(options = exp_results_demo.tracks.columns,value = 'StartFrequency', description='x_col: '),
    column_2 = widgets.Select(options = exp_results_demo.tracks.columns,value = 'Slope', description='y_col: '),
    mrk_sz = widgets.FloatSlider(value=.4, min=0,max=1.0,step=1e-2),
    alpha = widgets.FloatSlider(value=.5, min=0.0,max=1.0,step=1e-2), 
    frac_pts = widgets.FloatSlider(value=0.02,min=0.0,max=1.0,step=1e-2), 
    bins = widgets.IntSlider(value=200,min=50,max=700,step=10),
    fix_field = widgets.Checkbox(
    value=False,
    description='fix field',
    disabled=False,
    indent=False
)
):
    
    plt.close("all")
    scatt_settings={
            "figsize": (12, 4),
            "colors": ["b", "r", "g", "c", "m", "k"],
            "hist_bins": bins,
            "markersize": mrk_sz,
            "alpha": alpha,
        }
    exp_results_demo.scatter("tracks", column_1, column_2, fix_field = fix_field, field_value = field, scatt_settings = scatt_settings)

interactive(children=(Select(description='set_field: ', options=(0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 3…

### 2e: Visualize the relationship between different event attributes.

In [14]:
%matplotlib widget

set_fields = sorted(exp_results_demo.events['set_field'].unique().tolist())

plt.rcParams['figure.dpi']= 100
@interact
def scatter_plots(
    field = widgets.Select(options = set_fields,  description='set_field: '),
    column_1 = widgets.Select(options = exp_results_demo.events.columns,value = 'EventStartFreq', description='x_col: '),
    column_2 = widgets.Select(options = exp_results_demo.events.columns,value = 'EventSlope', description='y_col: '),
    mrk_sz = widgets.FloatSlider(value=.4, min=0,max=1.0,step=1e-2),
    alpha = widgets.FloatSlider(value=.5, min=0.0,max=1.0,step=1e-2), 
    frac_pts = widgets.FloatSlider(value=0.02,min=0.0,max=1.0,step=1e-2), 
    bins = widgets.IntSlider(value=200,min=50,max=700,step=10),
    fix_field = widgets.Checkbox(
    value=False,
    description='fix field',
    disabled=False,
    indent=False
)
):
    
    plt.close("all")
    scatt_settings={
            "figsize": (12, 4),
            "colors": ["b", "r", "g", "c", "m", "k"],
            "hist_bins": bins,
            "markersize": mrk_sz,
            "alpha": alpha,
        }
    exp_results_demo.scatter("events", column_1, column_2, fix_field = fix_field, field_value = field, scatt_settings = scatt_settings)

interactive(children=(Select(description='set_field: ', options=(0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2…