# Ne19_test_aid_0.

In [1]:
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd
import seaborn as sns
from datetime import datetime
import numpy as np

# Jupyter Lab imports.
import ipywidgets as widgets
from ipywidgets import interact, interact_manual, fixed

# Path to local imports.
sys.path.append("/home/drew/He6CRES/rocks_analysis_pipeline/")
from results import ExperimentResults
from rocks_utility import he6cres_db_query

## Step 0: Query the postgres database to see what run_ids to analyze.

In [11]:
query_run_log = '''
                    SELECT run_id, run_notes, set_field, created_at, EXTRACT(MONTH from created_at::date) as month
                    FROM he6cres_runs.run_log
                    WHERE num_spec_acq = 100 AND
                    EXTRACT(MONTH from created_at::date) = 10
                    ORDER BY run_id DESC 
                    LIMIT 80
                  '''

run_log = he6cres_db_query(query_run_log, local = True)

first_rid_per_field = run_log.groupby(["set_field"]).count()
display(first_rid_per_field)
display(run_log[:30])

he6_run_list = run_log.run_id.to_list()
he6_field_list = run_log.set_field.to_list()

print(" ".join(str(x) for x in he6_run_list[-57:]))
print(f"\n\n{len(he6_run_list)}")
print(" ".join(str(x) for x in he6_field_list[-57:]))

           run_id  run_notes  created_at  month
set_field
0.75            5          5           5      5
1.00            7          7           7      7
1.25            5          5           5      5
1.50            5          5           5      5
1.75            5          5           5      5
2.00           14         14          14     14
2.25            5          5           5      5
2.50            5          5           5      5
2.75            5          5           5      5
3.00            5          5           5      5
3.25            5          5           5      5

,run_id,run_notes,set_field,created_at,month
0,574,"Monitor Proportionality Test 3, Run 3/3. 2.0 T...",2.00,2022-10-07 05:59:22.855410,10.0
1,573,"Monitor Proportionality Test 3, Run 2/3. 2.0 T...",2.00,2022-10-07 05:49:53.000356,10.0
2,572,"Monitor Proportionality Test 3, Run 1/3. 2.0 T...",2.00,2022-10-07 05:39:59.244445,10.0
3,568,"Monitor Proportionality Test 2, Run 3/3. 2.0 T...",2.00,2022-10-07 04:35:32.482341,10.0
4,567,"Monitor Proportionality Test 2, Run 2/3. 2.0 T...",2.00,2022-10-07 04:25:25.048052,10.0
5,566,"Monitor Proportionality Test 2, Run 1/3. 2.0 T...",2.00,2022-10-07 04:14:38.890526,10.0
6,565,"Monitor Proportionality Test 1, Run 2/3. 2.0 T...",2.00,2022-10-07 03:35:29.387258,10.0
7,564,"Monitor Proportionality Test 1, Run 1/2. 2.0 T...",2.00,2022-10-07 03:25:15.121873,10.0
8,562,"Monitor Proportionality Test 1, Run 1/2. 2.0 T...",2.00,2022-10-07 03:12:51.170502,10.0
9,561,0.75T run 5/5. Note rga is not working. Ion ga...,0.75,2022-10-07 02:02:10.718327,10.0
10,560,0.75T run 4/5. Note rga is not working. Ion ga...,0.75,2022-10-07 01:52:18.892026,10.0
11,559,0.75T run 3/5. Note rga is not working. Ion ga...,0.75,2022-10-07 01:43:02.829758,10.0
12,558,0.75T run 2/5. Note rga is not working. Ion ga...,0.75,2022-10-07 01:32:58.573898,10.0
13,557,0.75T run 1/5. Note rga is not working. Ion ga...,0.75,2022-10-07 01:23:38.096859,10.0
14,555,1.00T run 5/5,1.00,2022-10-07 00:20:47.769983,10.0
15,554,1.00T run 4/5,1.00,2022-10-07 00:11:20.213224,10.0
16,553,1.00T run 3/5,1.00,2022-10-07 00:02:32.776352,10.0
17,552,1.00T run 2/5,1.00,2022-10-06 23:53:12.400337,10.0
18,551,1.00T run 1/5,1.00,2022-10-06 23:41:30.524827,10.0
19,549,1.00T run 2/5,1.00,2022-10-06 21:51:31.881759,10.0
20,548,1.00T run 1/5,1.00,2022-10-06 21:32:01.385208,10.0
21,546,1.25T run 5/5,1.25,2022-10-06 17:15:01.204194,10.0
22,545,1.25T run 4/5,1.25,2022-10-06 17:04:26.919350,10.0
23,544,1.25T run 3/5,1.25,2022-10-06 16:46:24.628233,10.0
24,543,1.25T run 2/5,1.25,2022-10-06 16:34:36.533655,10.0
25,542,1.25T run 1/5,1.25,2022-10-06 16:21:25.710881,10.0
26,540,1.50T run 5/5,1.50,2022-10-06 15:15:21.353911,10.0
27,539,1.50T run 4/5,1.50,2022-10-06 14:59:44.590072,10.0
28,538,1.50T run 3/5,1.50,2022-10-06 14:48:18.210908,10.0
29,537,1.50T run 2/5,1.50,2022-10-06 14:26:52.735150,10.0

561 560 559 558 557 555 554 553 552 551 549 548 546 545 544 543 542 540 539 538 537 536 534 533 532 531 530 528 527 526 525 524 522 521 520 519 518 516 515 514 513 512 510 509 508 507 506 504 503 502 501 500 496 495 494 493 492


66
0.75 0.75 0.75 0.75 0.75 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.25 1.25 1.25 1.25 1.25 1.5 1.5 1.5 1.5 1.5 1.75 1.75 1.75 1.75 1.75 2.0 2.0 2.0 2.0 2.0 2.25 2.25 2.25 2.25 2.25 2.5 2.5 2.5 2.5 2.5 2.75 2.75 2.75 2.75 2.75 3.0 3.0 3.0 3.0 3.0 3.25 3.25 3.25 3.25 3.25

## Step 1: Analyze the run_ids. 

* Follow the instructions in the [readme](https://github.com/Helium6CRES/rocks_analysis_pipeline).

## Step 2: Visualize the results and/or build a spectrum.

### 2a: Grab the experiment directory and root files from rocks.

In [3]:
local_dir = "/media/drew/T7 Shield/rocks_analysis/saved_experiments"
experiment_name = "ne19_test"
analysis_id = 0
include_root_files = True
max_root_files_to_grab = 5
rebuild_experiment_dir = False

In [4]:
exp_results_demo = ExperimentResults(local_dir = local_dir, 
                                     experiment_name = experiment_name, 
                                     analysis_id = analysis_id, 
                                     include_root_files = include_root_files,
                                     max_root_files_to_grab = max_root_files_to_grab,
                                     rebuild_experiment_dir=rebuild_experiment_dir,
                                    )

Keeping existing experiment directory.

Collecting root_files, tracks, and events.

All 55 root files are already present here: /media/drew/T7 Shield/rocks_analysis/saved_experiments/ne19_test_aid_0/root_files

### 2b: Look at the attributes of the exp_results_demo object.

In [5]:
exp_results_demo.root_files.head(3)

,run_id,spec_id,file_path,true_field,analysis_id,root_file_exists,file_id,rocks_file_path,exists,approx_slope,...,base_config_path,output_dir,noise_file_path,rocks_noise_file_path,root_file_path,pst_time,utc_time,monitor_rate,field,set_field
0,557,17272,/mnt/sdb/data/Freq_data_2022-10-06-18-13-24.spec,0.750156,0,True,0,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,True,5.127162e+08,...,/data/eliza4/he6_cres/katydid_analysis/base_co...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,/mnt/sdb/data/Freq_data_2022-10-05-19-34-17.spec,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,2022-10-06 18:13:24-07:00,2022-10-07 01:13:24+00:00,12070.00,0.750156,0.75
1,557,17273,/mnt/sdc/data/Freq_data_2022-10-06-18-13-28.spec,0.750156,0,True,1,/data/eliza4/he6_cres/sdc/data/Freq_data_2022-...,True,5.127162e+08,...,/data/eliza4/he6_cres/katydid_analysis/base_co...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,/mnt/sdb/data/Freq_data_2022-10-05-19-34-17.spec,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,2022-10-06 18:13:28-07:00,2022-10-07 01:13:28+00:00,12000.00,0.750156,0.75
2,557,17274,/mnt/sdd/data/Freq_data_2022-10-06-18-13-32.spec,0.750156,0,True,2,/data/eliza4/he6_cres/sdd/data/Freq_data_2022-...,True,5.127162e+08,...,/data/eliza4/he6_cres/katydid_analysis/base_co...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,/mnt/sdb/data/Freq_data_2022-10-05-19-34-17.spec,/data/eliza4/he6_cres/sdb/data/Freq_data_2022-...,/data/eliza4/he6_cres/katydid_analysis/root_fi...,2022-10-06 18:13:32-07:00,2022-10-07 01:13:32+00:00,12132.13,0.750155,0.75

In [ ]:
exp_results_demo.tracks.head(3)

In [ ]:
exp_results_demo.events.head(3)

## Are all the desired fields present?

In [7]:
exp_results_demo.root_files.set_field.unique()

array([0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25])

In [13]:
exp_results_demo.events.groupby([ "file_id"]).EventID.count().reset_index()

    file_id  EventID
0         0       55
1         1       49
2         2       51
3         3       50
4         4       65
5         5       43
6         6       52
7         7       58
8         8       54
9         9       67
10       10       41
11       11       41
12       12       54
13       13       63
14       14       39
15       15       55
16       16       46
17       17       57
18       18       53
19       19       49
20       20       39
21       21       41
22       22       51
23       23       73
24       24       55
25       25       52
26       26       52
27       27       55
28       28       46
29       29       43
30       30       49
31       31       42
32       32       57
33       33       51
34       34       46
35       35       60
36       36       60
37       37       55
38       38       65
39       39       61
40       40       44
41       41       43
42       42       50
43       43       57
44       44       54
45       45       48
46       46       51
47       47       60
48       48       69
49       49       36

### 2c: Visualize the quality of track and event reconstruction.

In [ ]:
%matplotlib widget

plt.rcParams['figure.dpi']= 100

@interact
def analysis_viz(
    run_id = widgets.Select(options = exp_results_demo.run_ids, description='run_id: '),
    file_id = widgets.Select(options = exp_results_demo.file_ids, description='file_id: '),
    events = widgets.Checkbox(True, description='events'),
    tracks = widgets.Checkbox(False, description='tracks'),
    sparse = widgets.Checkbox(False, description='sparse_spec'),
    EventID = widgets.IntSlider(value=1,min=1,max=20,step=1),
    mrk_sz = widgets.FloatSlider(value=.08,min=0,max=1.0,step=1e-2),
    alpha = widgets.FloatSlider(value=1.0,min=0.0,max=1.0,step=1e-2), 
    frac_pts = widgets.FloatSlider(value=.7,min=0.0,max=1.0,step=1e-2),
):

    config = {"tracks": {"show": tracks,  "alpha": alpha, "EventIDs":[EventID]}, 
              "events": {"show": events, "alpha": alpha}, 
              "sparse_spec": {"show": sparse, "frac_pts": frac_pts,  "alpha": alpha, "mrk_sz": mrk_sz}}
    
    exp_results_demo.visualize(run_id, file_id, config)

### 2d: Visualize the relationship between different track attributes.

In [ ]:
%matplotlib widget

set_fields = sorted(exp_results_demo.tracks['set_field'].unique().tolist())

plt.rcParams['figure.dpi']= 100
@interact
def scatter_plots(
    field = widgets.Select(options = set_fields,  description='set_field: '),
    column_1 = widgets.Select(options = exp_results_demo.tracks.columns,value = 'StartFrequency', description='x_col: '),
    column_2 = widgets.Select(options = exp_results_demo.tracks.columns,value = 'Slope', description='y_col: '),
    mrk_sz = widgets.FloatSlider(value=.4, min=0,max=1.0,step=1e-2),
    alpha = widgets.FloatSlider(value=.5, min=0.0,max=1.0,step=1e-2), 
    frac_pts = widgets.FloatSlider(value=0.02,min=0.0,max=1.0,step=1e-2), 
    bins = widgets.IntSlider(value=200,min=50,max=700,step=10),
    fix_field = widgets.Checkbox(
    value=False,
    description='fix field',
    disabled=False,
    indent=False
)
):
    
    plt.close("all")
    scatt_settings={
            "figsize": (12, 4),
            "colors": ["b", "r", "g", "c", "m", "k"],
            "hist_bins": bins,
            "markersize": mrk_sz,
            "alpha": alpha,
        }
    exp_results_demo.scatter("tracks", column_1, column_2, fix_field = fix_field, field_value = field, scatt_settings = scatt_settings)

### 2e: Visualize the relationship between different event attributes.

In [6]:
%matplotlib widget

set_fields = sorted(exp_results_demo.events['set_field'].unique().tolist())

plt.rcParams['figure.dpi']= 100
@interact
def scatter_plots(
    field = widgets.Select(options = set_fields,  description='set_field: '),
    column_1 = widgets.Select(options = exp_results_demo.events.columns,value = 'EventStartFreq', description='x_col: '),
    column_2 = widgets.Select(options = exp_results_demo.events.columns,value = 'EventSlope', description='y_col: '),
    mrk_sz = widgets.FloatSlider(value=.4, min=0,max=1.0,step=1e-2),
    alpha = widgets.FloatSlider(value=.5, min=0.0,max=1.0,step=1e-2), 
    frac_pts = widgets.FloatSlider(value=0.02,min=0.0,max=1.0,step=1e-2), 
    bins = widgets.IntSlider(value=200,min=50,max=700,step=10),
    fix_field = widgets.Checkbox(
    value=False,
    description='fix field',
    disabled=False,
    indent=False
)
):
    
    plt.close("all")
    scatt_settings={
            "figsize": (12, 4),
            "colors": ["b", "r", "g", "c", "m", "k"],
            "hist_bins": bins,
            "markersize": mrk_sz,
            "alpha": alpha,
        }
    exp_results_demo.scatter("events", column_1, column_2, fix_field = fix_field, field_value = field, scatt_settings = scatt_settings)

interactive(children=(Select(description='set_field: ', options=(0.75, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, …